################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/DSP/Source/StatisticsFunctions/%.o Drivers/DSP/Source/StatisticsFunctions/%.su Drivers/DSP/Source/StatisticsFunctions/%.cyclo: ../Drivers/DSP/Source/StatisticsFunctions/%.c Drivers/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -D__FPU_PRESENT=1 -DUSE_HAL_DRIVER -DSTM32G491xx -c -I../Core/Inc -I../Drivers/DSP/ComputeLibrary/Include -I../Drivers/DSP/Include -I../Drivers/DSP/PrivateInclude -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-Drivers-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Drivers/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.d
	-$(RM) ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.d
	-$(RM) ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_max_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_min_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo
	-$(RM) ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_power_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.d ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.o ./Drivers/DSP/Source/StatisticsFunctions/arm_power_q7.su ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_std_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_std_q31.su ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.d ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.o ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f16.su ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.d ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.o ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f32.su ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.d ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.o ./Drivers/DSP/Source/StatisticsFunctions/arm_var_f64.su ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.d ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.o ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q15.su ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.d ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.o ./Drivers/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Drivers-2f-DSP-2f-Source-2f-StatisticsFunctions

